# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.8.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check formatting with isort and black
      run: |
        isort . --check-only && black . --check
    - name: Lint with flake8
      run: |
        # stop the build if there are any flake8 issues
        flake8 . --count --show-source --statistics --extend-ignore=F541,E203 --max-line-length=88
    - name: Type check with mypy
      run: |
        mypy .
    - name: Test with pytest
      run: |
        pytest
