name: Chek formatting, lint and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.8.12"
    - name: Install dependencies
      run: |
        pip install -e .[dev]
    - name: Check formatting with isort and black
      run: |
        isort . --check-only && black . --check
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics --extend-ignore=E203,E231,F541 --max-line-length=88
    - name: Type check with mypy - except for GUI
      run: |
        mypy . --exclude=gui
    - name: Test with pytest
      run: |
        pytest
    - name: Install GUI dependencies and type check
      run: |
        pip install -e .[GUI]
        mypy gui/